// <auto-generated />
using Entity003.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entity003.Models.Migrations
{
    [DbContext(typeof(AireDbContext))]
    [Migration("20250919214103_AddPonetoAireline")]
    partial class AddPonetoAireline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entity003.Models.AireLine", b =>
                {
                    b.Property<int>("AireLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AireLineId"), 1L, 2);

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("AireLineAdress");

                    b.Property<string>("AireLine_Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AireLineId");

                    b.ToTable("AireLine");
                });

            modelBuilder.Entity("Entity003.Models.Phones", b =>
                {
                    b.Property<string>("Phonenumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("AireLine_Id")
                        .HasColumnType("int");

                    b.HasKey("Phonenumber", "AireLine_Id");

                    b.HasIndex("AireLine_Id");

                    b.ToTable("Phones");
                });

            modelBuilder.Entity("Entity003.Models.Phones", b =>
                {
                    b.HasOne("Entity003.Models.AireLine", null)
                        .WithMany("AirelinePhones")
                        .HasForeignKey("AireLine_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Entity003.Models.AireLine", b =>
                {
                    b.Navigation("AirelinePhones");
                });
#pragma warning restore 612, 618
        }
    }
}
