// <auto-generated />
using System;
using Entity003.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entity003.Models.Migrations
{
    [DbContext(typeof(AireDbContext))]
    [Migration("20250924032648_add")]
    partial class add
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entity003.Models.AireCraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AireLineOwnerId")
                        .HasColumnType("int");

                    b.Property<int>("Capcity")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AireLineOwnerId");

                    b.ToTable("AireCraft");
                });

            modelBuilder.Entity("Entity003.Models.AireCraftRoute", b =>
                {
                    b.Property<int>("AireCraftId")
                        .HasColumnType("int");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Arrival")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Departure")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<int>("Num_of_Passengers")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AireCraftId", "RouteId");

                    b.HasIndex("RouteId");

                    b.ToTable("AireCraftRoute");
                });

            modelBuilder.Entity("Entity003.Models.AireLine", b =>
                {
                    b.Property<int>("AireLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AireLineId"), 1L, 2);

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("AireLineAdress");

                    b.Property<string>("AireLine_Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AireLineId");

                    b.ToTable("AireLine");
                });

            modelBuilder.Entity("Entity003.Models.Employee", b =>
                {
                    b.Property<int>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("AireId")
                        .HasColumnType("int");

                    b.Property<int>("BD_Day")
                        .HasColumnType("int");

                    b.Property<int>("BD_Month")
                        .HasColumnType("int");

                    b.Property<int>("BD_Year")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("EmployeeName");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmpId");

                    b.HasIndex("AireId");

                    b.ToTable("employess", (string)null);
                });

            modelBuilder.Entity("Entity003.Models.Phones", b =>
                {
                    b.Property<string>("Phonenumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("AireLine_Id")
                        .HasColumnType("int");

                    b.HasKey("Phonenumber", "AireLine_Id");

                    b.HasIndex("AireLine_Id");

                    b.ToTable("Phones");
                });

            modelBuilder.Entity("Entity003.Models.Qualifacion", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Qualificatons")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EmployeeId", "Qualificatons");

                    b.ToTable("employeeQualifications", (string)null);
                });

            modelBuilder.Entity("Entity003.Models.Route", b =>
                {
                    b.Property<int>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RouteId"));

                    b.Property<string>("Calssification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Distance")
                        .HasColumnType("int");

                    b.Property<string>("Distnation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RouteId");

                    b.ToTable("Route");
                });

            modelBuilder.Entity("Entity003.Models.Transaction", b =>
                {
                    b.Property<int>("TransactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactId"));

                    b.Property<int>("AireLineId")
                        .HasColumnType("int");

                    b.Property<int>("Amuont")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("discription")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.HasKey("TransactId");

                    b.HasIndex("AireLineId");

                    b.ToTable("aireLineTransaction", (string)null);
                });

            modelBuilder.Entity("Entity003.Models.AireCraft", b =>
                {
                    b.HasOne("Entity003.Models.AireLine", "AireLineOwner")
                        .WithMany("airecraftsOwned")
                        .HasForeignKey("AireLineOwnerId");

                    b.OwnsOne("Entity003.Models.Crew", "crewDetails", b1 =>
                        {
                            b1.Property<int>("AireCraftId")
                                .HasColumnType("int");

                            b1.Property<string>("AssitantPilot")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Host1")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Host2")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("MajorPilot")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("AireCraftId");

                            b1.ToTable("AireCraft");

                            b1.WithOwner()
                                .HasForeignKey("AireCraftId");
                        });

                    b.Navigation("AireLineOwner");

                    b.Navigation("crewDetails")
                        .IsRequired();
                });

            modelBuilder.Entity("Entity003.Models.AireCraftRoute", b =>
                {
                    b.HasOne("Entity003.Models.AireCraft", "AireCraft")
                        .WithMany("AireCraftAssign")
                        .HasForeignKey("AireCraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity003.Models.Route", "Routes")
                        .WithMany("routes")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AireCraft");

                    b.Navigation("Routes");
                });

            modelBuilder.Entity("Entity003.Models.Employee", b =>
                {
                    b.HasOne("Entity003.Models.AireLine", "AireLine")
                        .WithMany("employeesworks")
                        .HasForeignKey("AireId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AireLine");
                });

            modelBuilder.Entity("Entity003.Models.Phones", b =>
                {
                    b.HasOne("Entity003.Models.AireLine", null)
                        .WithMany("AirelinePhones")
                        .HasForeignKey("AireLine_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Entity003.Models.Qualifacion", b =>
                {
                    b.HasOne("Entity003.Models.Employee", null)
                        .WithMany("EmpQualifications")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entity003.Models.Transaction", b =>
                {
                    b.HasOne("Entity003.Models.AireLine", "aireLine")
                        .WithMany("transactions")
                        .HasForeignKey("AireLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("aireLine");
                });

            modelBuilder.Entity("Entity003.Models.AireCraft", b =>
                {
                    b.Navigation("AireCraftAssign");
                });

            modelBuilder.Entity("Entity003.Models.AireLine", b =>
                {
                    b.Navigation("AirelinePhones");

                    b.Navigation("airecraftsOwned");

                    b.Navigation("employeesworks");

                    b.Navigation("transactions");
                });

            modelBuilder.Entity("Entity003.Models.Employee", b =>
                {
                    b.Navigation("EmpQualifications");
                });

            modelBuilder.Entity("Entity003.Models.Route", b =>
                {
                    b.Navigation("routes");
                });
#pragma warning restore 612, 618
        }
    }
}
